### ISSUE TITLE
Game crashed after pressing "Live Camera" or starting a match with Set Online Local/Remote enabled.

### ISSUE THREAD

**Issue by Zigaru** [Kiloutre/TekkenMovesetExtractor#106]
This seems to be the error shown. Thanks in advance!

Exception in thread Thread-1 (liveControlLoop):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "GUI_TekkenCameraAnimator.py", line 2070, in liveControlLoop
  File "GUI_TekkenCameraAnimator.py", line 2333, in waitSingleFrame
  File "Addresses.py", line 180, in readInt
  File "Addresses.py", line 172, in readBytes
Exception: Could not read memory addr "7ff723c1a034" (4 bytes): invalid address or process closed?

Things I have attempted :
My game's up to date and I have verified local files already. 
I'm on 1.0.32.38, Updating game addresses shows 'nothing to update'
Removing all mods (still crashes)

The tool worked just fine a day ago. There's also no in-game update, which confuses me as to why this happened.

![image](https://user-images.githubusercontent.com/127212411/223446072-159a100f-4d58-4840-a47f-0fc23244ff87.png)

**Comment by Zigaru** [comment]
![image](https://user-images.githubusercontent.com/127212411/223445006-b2c6fa03-fbe2-4e8c-9c31-26cedf8784b7.png)

**Comment by Zigaru** [comment]
NVM APPARENTLY THERE WAS AN UPDATE LMAO, I'll be waiting patiently for the patch then. TYSM Kilo and co!

**Comment by Zigaru** [comment]
Fixed as of 10/03/23, thanks Kilo!
