### ISSUE TITLE
Dear boss,I using this program have a error, please help

### ISSUE THREAD

**Issue by jrksaucy** [Kiloutre/TekkenMovesetExtractor#17]
Dear boss,I use this program try to export two character(baek and wang) movedata have a problem.
my english is poor , so i hope you can read

i downloaded two game IMG same error display this info:
Exception in Tkinter callback
Traceback (most recent call last):
   File "tkinter\__init__.py", line 1702, in __call__
   File "GUI_TekkenMovesetExtractor.py", line 629, in <lambda>
   File "GUI_TekkenMovesetExtractor.py", line 325, in exportTag2Character
TypeError:unsupported operand type(s) for +=: 'int' and 'NoneType'

there only two game IMG can be download in china

one IMG URL:https://pan.baidu.com/s/1VyS97QdxZirMvdZvzhOPzQ#list/path=%2F
CEMU can not search and display it in game list,it can be open Tekken.rpx to run,but export error

two IMG URL:https://pan.baidu.com/s/1nuKhEf3#list/path=%2F
this IMG is WUP type,use CDecrypt to Loadiine,it can be search and display in CEMU game list,but the version is 0
try to running game,[JPN v0] in title, like this "[TitleId:00050000-10100600] TEKKEN TAG 2 Wii U EDITION [JPN v0] "
I saw two Player addresses in the game_addresses.txt like:
00050000-1010f800_p1_addr = 0x10885C90 #Game ID: 00050000-1010f800 [EU v32]
00050000-10110000_p1_addr = 0x10884C70 #Game ID: 00050000-10110000 [US v16]
mabye export cannot suport [JPN v0] ?

how can i fix it please?
mabye you can teach me some way find Player addresses on [JPN v0] ?
or export the Character"baek"and"wang" movedata publish in the Releases?

**Comment by jrksaucy** [comment]
The problem is solved， just fix titleID
