### ISSUE TITLE
I can't edit move's frames

### ISSUE THREAD

**Issue by Warmsie** [Kiloutre/TekkenMovesetExtractor#30]
I just get this error message in the main window for TekkenMovesetExtractor, whenever I try to edit anything.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "GUI_TekkenMovesetEditor.py", line 827, in save
  File "GUI_TekkenMovesetEditor.py", line 407, in validateField
  File "c:\program files\python36\lib\re.py", line 172, in match
  File "c:\program files\python36\lib\re.py", line 301, in _compile
  File "c:\program files\python36\lib\sre_compile.py", line 562, in compile
  File "c:\program files\python36\lib\sre_parse.py", line 855, in parse
  File "c:\program files\python36\lib\sre_parse.py", line 416, in _parse_sub
  File "c:\program files\python36\lib\sre_parse.py", line 616, in _parse
sre_constants.error: nothing to repeat at position 1

**Comment by Warmsie** [comment]
It downloaded the newest version again it works.
